SELECT DISTINCT AAP.PATCH_NAME,AAP.PATCH_TYPE,AAP.CREATION_DATE,APRB.APPLICATION_SHORT_NAME MODULE
FROM AD_APPLIED_PATCHES AAP,ad_patch_run_bugs APRB
WHERE AAP.PATCH_NAME=APRB.ORIG_BUG_NUMBER AND AAP.creation_date > '13-MAY-08'
