SELECT FCQ.CONCURRENT_QUEUE_ID,FCQ.CONCURRENT_QUEUE_NAME,FCR.PHASE_CODE,FCR.STATUS_CODE,fcp.logfile_name FROM
fnd_concurrent_queues_vl FCQ,FND_CONCURRENT_PROCESSES FCP,FND_CONCURRENT_REQUESTS FCR WHERE
FCQ.CONCURRENT_QUEUE_ID=FCP.CONCURRENT_QUEUE_ID AND FCP.CONCURRENT_PROCESS_ID=FCR.CONTROLLING_MANAGER AND
FCR.REQUEST_ID=&1
