SELECT FCR.REQUEST_ID,FCP.CONCURRENT_PROGRAM_NAME,to_char(FCR.REQUEST_DATE,'DD-MON-YYYY HH24:MI:SS') REQUEST_DATE,
FCR.REQUESTED_BY,FCR.PHASE_CODE,FCR.STATUS_CODE,FU.USER_NAME,FRV.RESPONSIBILITY_NAME,(SYSDATE-FCR.REQUEST_DATE)*24*60 RUNNING_TIME
FROM FND_CONCURRENT_REQUESTS FCR,
     FND_USER FU,
     FND_RESPONSIBILITY_VL FRV,
     FND_CONCURRENT_PROGRAMS FCP
WHERE FCR.REQUESTED_BY=FU.USER_ID 
AND FCR.RESPONSIBILITY_ID=FRV.RESPONSIBILITY_ID
AND FCP.CONCURRENT_PROGRAM_ID=FCR.CONCURRENT_PROGRAM_ID 
AND FCR.PHASE_CODE='R' 
AND SYSDATE-1/24 > REQUEST_DATE
